# RISC-V options.

[CONFIG_ARCH_RISCV]
type = "int"
value = "{ARCH_BITS}"
header = true
help = "RISC-V register width (XLEN)"

[CONFIG_RISCV_COMPRESSED]
type = "bool"
default = true
group = "build"
help = "Compressed ('c') instruction extension"
