# arm64 options and default overrides.

[CROSS_COMPILE]
default = "aarch64-none-elf-"

[PLATFORM]
default = "virt"

[CONFIG_ARM64_SEMIHOSTING]
type = "bool"
default = false
group = "build"
header = true
help = "Early console via QEMU semihosting"
