#!/bin/bash

set -e

echo "#ifndef _GENERATED_ASM_DEFINES_H"
echo "#define _GENERATED_ASM_DEFINES_H"
echo "/*"
echo " * This file is autogenerated. If you need to change it,"
echo " * edit asm-defines.c instead."
echo " *"
echo " * ALL MANUAL CHANGES TO THIS FILE WILL BE LOST!"
echo " */"
echo ""
sed -ne "/^=>/{s:=>#\(.*\):/* \1 */:; s:^=>\([^ ]*\) [\$#]*\([-0-9]*\) \(.*\):#define \1 \2 /* \3 */:; s:^=>\([^ ]*\) [\$#]*\([^ ]*\) \(.*\):#define \1 \2 /* \3 */:; s:=>::; p;}" $1
echo "";
echo "#endif"
