#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
#
# Grinch, a minimalist operating system
#
# Copyright (c) OTH Regensburg, 2026
#
# Authors:
#  Ralf Ramsauer <ralf.ramsauer@oth-regensburg.de>
"""Generate config.mk and config.h from per-directory config.toml files.

config.mk holds the tunable option values and is the source of truth:
existing values are preserved, newly declared options are added with their
default (olddefconfig). config.h is then derived from config.mk plus the
declarations. --defconfig ignores existing values and resets to defaults.

Option fields: type (bool|int|string), group, and either
  default   a user-tunable value, stored in config.mk, or
  value     a fixed value (may use {ARCH}/{ARCH_BITS}), header-only.
header = true also emits the option to config.h.
"""
import argparse
import re
import sys
import tomllib
from pathlib import Path

GROUPS = [("arch", "Architecture"), ("compiler", "Compiler"),
          ("build", "Build options"), ("qemu", "QEMU runtime")]

MK_HEADER = "# Auto-generated by scripts/config.py. Edit values; 'make defconfig' resets."
H_HEADER = "/* Auto-generated from config.mk. Do not edit. */"


def load_decls(paths, subs):
    """Merge declarations in order; a later file may override an option's
    fields (e.g. an arch-specific default). Expand {ARCH}/{ARCH_BITS}."""
    decls = {}
    for p in paths:
        if not p.exists():
            continue
        for name, spec in tomllib.loads(p.read_text()).items():
            decls.setdefault(name, {}).update(spec)
    for name, spec in decls.items():
        for key in ("default", "value"):
            if isinstance(spec.get(key), str):
                spec[key] = spec[key].format(**subs)
        if "default" in spec and "group" not in spec:
            sys.exit(f"config: tunable {name} needs a group")
    return decls


def read_values(path):
    """Parse config.mk into {name: raw_value} (quotes stripped)."""
    values = {}
    if path.exists():
        for line in path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, val = line.partition("=")
                values[key.strip()] = val.strip()
    return values


def write_if_changed(path, text):
    if path.exists() and path.read_text() == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".new")
    tmp.write_text(text)
    tmp.replace(path)
    return True


def resolved(spec, raw):
    """Effective value string of a tunable, given its raw config.mk value."""
    if raw is not None:
        return raw
    return "" if spec["type"] == "bool" and not spec["default"] else \
        "1" if spec["type"] == "bool" else str(spec["default"])


def render_mk(decls, values):
    out = [MK_HEADER]
    for gkey, label in GROUPS:
        names = [n for n, s in decls.items()
                 if "default" in s and s.get("group") == gkey]
        if not names:
            continue
        out.append(f"\n# {label}")
        for n in names:
            out.append(f"{n}={resolved(decls[n], values.get(n))}")
    return "\n".join(out) + "\n"


def render_h(decls, values):
    out = [H_HEADER]
    for n, s in decls.items():
        hdr = s.get("header")
        if not hdr:
            continue
        name = hdr if isinstance(hdr, str) else n     # 'header' may rename
        if "value" in s:                              # fixed constant
            v = s["value"]
        elif s["type"] == "bool":
            if values.get(n) != "1":                  # omit when off (#ifdef)
                continue
            out.append(f"#define {name} 1")
            continue
        else:
            v = resolved(s, values.get(n))
        out.append(f'#define {name} "{v}"' if s["type"] == "string" else f"#define {name} {v}")
    return "\n".join(out) + "\n"


def arch_super(arch):
    """Map an ARCH to its arch/ source directory."""
    if arch.startswith("arm"):
        return "arm64"
    if arch.startswith("riscv"):
        return "riscv"
    sys.exit(f"config: unknown architecture {arch}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--arch", required=True)
    ap.add_argument("--config-mk", type=Path, required=True)
    ap.add_argument("--config-h", type=Path, required=True)
    ap.add_argument("--defconfig", action="store_true")
    ap.add_argument("--set", action="append", metavar="KEY=VALUE", default=[])
    args = ap.parse_args()

    srctree = Path(__file__).resolve().parent.parent
    bits = re.search(r"\d+$", args.arch)
    subs = {"ARCH": args.arch, "ARCH_BITS": bits.group() if bits else ""}
    decls = load_decls([srctree / "config.toml",
                        srctree / "arch" / arch_super(args.arch) / "config.toml"], subs)

    existing = read_values(args.config_mk)
    values = {} if args.defconfig else existing.copy()
    for kv in args.set:
        k, _, v = kv.partition("=")
        k = k.strip()
        if k in decls and "default" in decls[k] and k not in existing:
            values[k] = v.strip()
    values["ARCH"] = args.arch

    changed = []
    if write_if_changed(args.config_mk, render_mk(decls, values)):
        changed.append(args.config_mk.name)
    values = read_values(args.config_mk)          # config.h derives from it
    if write_if_changed(args.config_h, render_h(decls, values)):
        changed.append(args.config_h.name)
    if changed:
        print(" ".join(changed))


if __name__ == "__main__":
    main()
