#!/bin/bash

set -e

output=$(realpath $1)
shift

tmp=$(mktemp -d)

mkdir $tmp/bin
mkdir $tmp/dtb

cp -a user/apps/build/* $tmp/bin/
cp -a res/logo.gimg res/test.txt $tmp/
cp -a kernel.bin $tmp/

cd $tmp
find . -print | cpio -ov -H newc > $output 2>/dev/null

rm -rf $tmp
