#!/usr/bin/env bash

set -e

output=$(realpath $1)
bindir=$2
shift 2

tmp=$(mktemp -d)

mkdir $tmp/bin

cp -a "$bindir"/* "$tmp/bin/"

dest="$tmp/bin"
for f in "$@"; do
	if [ "$f" = "--" ]; then
		dest="$tmp"
		continue
	fi
	cp -a "$f" "$dest/"
done

cd $tmp
find . -print | cpio -ov -H newc > $output 2>/dev/null

rm -rf $tmp
