#!/usr/bin/env python3
#
# Grinch, a minimalist operating system
#
# Copyright (c) OTH Regensburg, 2024
#
# Authors:
#  Ralf Ramsauer <ralf.ramsauer@oth-regensburg.de>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.

import sys
import struct

from PIL import Image

f_in = sys.argv[1]
f_out = sys.argv[2]

width = 320
height = 240

im = Image.open(f_in)

im = im.resize((width, height))
pix = im.load()

imgdata = struct.pack('II', width, height)

for y in range(0,height):
    for x in range(0, width):
        r, g, b = pix[x, y]
        imgdata += struct.pack('BBB', r, g, b)

with open(f_out, 'wb') as f:
    f.write(imgdata)
